#LAB8

In [3]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Step 1: Load Data
from google.colab import drive
drive.mount('/content/drive')

datasets = pd.read_csv('/content/drive/My Drive/Colab Notebooks/spam1.csv') 
datasets.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

     v1                                                 v2
0  spam  Free entry in 2 a wkly comp to win FA Cup fina...
1  spam  FreeMsg Hey there darling it's been 3 week's n...
2  spam  WINNER!! As a valued network customer you have...
3  spam  Had your mobile 11 months or more? U R entitle...
4  spam  SIX chances to win CASH! From 100 to 20,000 po...

In [5]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

dataset = datasets
			
dataset = pd.DataFrame(dataset)
dataset.columns = ["v2", "v1"]

nltk.download('stopwords')

dataset

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

       v2                                                 v1
0    spam  Free entry in 2 a wkly comp to win FA Cup fina...
1    spam  FreeMsg Hey there darling it's been 3 week's n...
2    spam  WINNER!! As a valued network customer you have...
3    spam  Had your mobile 11 months or more? U R entitle...
4    spam  SIX chances to win CASH! From 100 to 20,000 po...
..    ...                                                ...
508  spam  This is the 2nd time we have tried 2 contact u...
509   ham              Will �_ b going to esplanade fr home?
510   ham  Pity, * was in mood for that. So...any other s...
511   ham  The guy did some bitching but I acted like i'd...
512   ham                         Rofl. Its true to its name

[513 rows x 2 columns]

In [ ]:
corpus = []

#dataset[col][row]

for i in range(0, 513):
	text = re.sub('[^a-zA-Z]', '', dataset['v2'][i])
	text = text.lower()
	text = text.split()
	ps = PorterStemmer()
	text = ''.join(text)
	corpus.append(text)

# corpus

# creating bag of words model
cv = CountVectorizer(max_features = 1500)

X = cv.fit_transform(corpus).toarray()
y =  dataset.iloc[:, 1].values
print(X)
print(y)

In [13]:
# splitting the data set into training set and test set
import sklearn
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
		X, y, test_size = 0.25, random_state = 98)

In [14]:
#import Multnomial 
# fitting naive bayes to the training set
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

classifier = MultinomialNB();
classifier.fit(X_train, y_train)

# predicting test set results
y_pred = classifier.predict(X_test)

# making the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
#accuracy
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.0

On the spam2

In [32]:
datasets2 = pd.read_csv('/content/drive/My Drive/Colab Notebooks/spam2.csv') 
datasets2.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [33]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

dataset2 = datasets2
			
dataset2 = pd.DataFrame(dataset2)
dataset2.columns = ["v2", "v1"]

nltk.download('stopwords')

dataset2

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

        v2                                                 v1
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [46]:
corpus = []

#dataset[col][row]

for i in range(0, 5572):
	text = re.sub('[^a-zA-Z]', '', dataset2['v2'][i])
	text = text.lower()
	text = text.split()
	ps = PorterStemmer()
	text = ''.join(text)
	corpus.append(text)

# corpus

# creating bag of words model
cv = CountVectorizer(max_features = 1500)

X = cv.fit_transform(corpus).toarray()
y =  dataset2.iloc[:, 1].values
print(X)
print(y)

[[1 0]
 [1 0]
 [0 1]
 ...
 [1 0]
 [1 0]
 [1 0]]
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']

In [54]:
# splitting the data set into training set and test set
import sklearn
from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(
		X, y, test_size = 0.25, random_state = 98)

In [55]:
#import Multnomial 
# fitting naive bayes to the training set
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

classifier = MultinomialNB();
classifier.fit(X_train1, y_train1)

# predicting test set results
y_pred1 = classifier.predict(X_test1)

# making the confusion matrix
cm1 = confusion_matrix(y_test1, y_pred1)
cm1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [56]:
#accuracy
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred1))

Accuracy: 0.003589375448671931